
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('my_first_dbt_model')
              field: id


  - name: snowflake_cust_purchases
    description: "The total purchases for each customer"
    columns:
      - name: c_custkey
        tests:
          - unique
          - not_null

  - name: cumulative_orders_by_date
    description: "Cumulative Order total by Date"
    columns:
      - name: o_orderdate
        tests:
          - unique
          - not_null

  - name: playing_with_tests
    columns:
      - name: c_custkey
        tests:
          - not_null
          - unique
      - name: c_mktsegment
        tests:
          - accepted_values:
              values: ['BUILDING','AUTOMOBILE','MACHINERY','HOUSEHOLD','FURNITURE']
